spring:
  application:
    name: liempt-property-access-service
  config:
    import: optional:configserver:http://localhost:8888
    
server:
  port: ${port:8100}
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
